export { default as SalesList } from "./SalesList";
export { default as Header } from "./Header";
export { default as UserAvatar } from "./UserAvatar";
export { default as ImgSwiper } from "./ImgSwiper";
export { default as Footer } from "./Footer";
export { default as AsideMobile } from "./Aside/AsideMobile";
export { default as AsideDesktop } from "./Aside/AsidePc";
export { default as Button } from "./Buttons";
export { default as Banner } from "./Banner";
export { default as ChangePage } from "./ChangePage";
export { default as Modal } from "./Modal";
export { default as CreateAdForm } from "./Forms/CreateAdForm";
// export { default as SalesComments } from "./SaleComments";
